Exclude bin/setup and bin/console from the gem
These are common names and easily conflict with other gems. They're only
for local use, no need to ship them.

```
ERROR:  Error installing veil-0.3.0.gem:
	"console" from veil conflicts with installed executable from wisper
```

Signed-off-by: Bryan McLellan <btm@loftninjas.org>